6module-2task
js-tasks-ru/jsbasic-20240321_asaulsergey pull request #11
Opened 2024-04-24 21:24 UTC by Serega560

2024-04-24 21:24 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-04-27 10:05 UTC, SinimaWath requested changes
Nen dct h

2024-04-27 10:05 UTC, SinimaWath commented on 6-module/2-task/index.js
> +    this.elem.setAttribute('id', `${this.#card.id}`);
Этот аттрибут надо выставить в функции `#template`, так же как и `this.#card.name`, `this.#card.image`, `this.#card.price`

2024-04-27 10:05 UTC, SinimaWath commented on 6-module/2-task/index.js
> +    this.elem.querySelector('.card__button').addEventListener('click', this.#productClick.bind(this));
`bind(this)` тут не нужен, так как `#productClick` - стрелочная функция

2024-04-27 16:51 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-04-29 17:05 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-05-01 11:36 UTC, SinimaWath approved these changes

2024-05-01 11:36 UTC, merged